export const LIGHT_THEME = 'LIGHT_THEME';
export const DARK_THEME = 'DARK_THEME';

export const FAHRENHIT = 'FAHRENHIT';
export const CELSIUS = 'CELSIUS';

export const AUTOCOMPLETE_SEARCH_LIST_PENDING = 'AUTOCOMPLETE_SEARCH_LIST_PENDING';
export const AUTOCOMPLETE_SEARCH_LIST_SUCCESS = 'AUTOCOMPLETE_SEARCH_LIST_SUCCESS';
export const AUTOCOMPLETE_SEARCH_LIST_FAIL = 'AUTOCOMPLETE_SEARCH_LIST_FAIL';

export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';

export const FETCH_FIVE_DAYS_DATA_PENDING = 'FETCH_FIVE_DAYS_DATA_PENDING';
export const FETCH_FIVE_DAYS_DATA_SUCCESS = 'FETCH_FIVE_DAYS_DATA_SUCCESS';
export const FETCH_FIVE_DAYS_DATA_FAIL = 'FETCH_FIVE_DAYS_DATA_FAIL';

export const UPDATE_FAVORITE_LOCATION = 'UPDATE_FAVORITE_LOCATION';

export const FETCH_MY_DATA_PENDING = 'FETCH_MY_DATA_PENDING';
export const FETCH_MY_DATA_SUCCESS = 'FETCH_MY_DATA_SUCCESS';
export const FETCH_MY_DATA_FAIL = 'FETCH_MY_DATA_FAIL';